DROP TABLE IF EXISTS Example;
DROP TABLE IF EXISTS loggedInUsers;

CREATE TABLE Example (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  contents TEXT NOT NULL
);

CREATE TABLE loggedInUsers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL
);
